### ISSUE TITLE
unhandled exception Windows 7

### ISSUE THREAD

**Issue by cmorgan** [Wintellect/FastFileFinder#6]
i'm in need of fast search on Windoze, but got this with ff.exe

Unhandled Exception: System.MissingMethodException: Method not found: 'System.Text.StringBuilder System.Text.StringBuilder.AppendFormat(System.IFormatProvider, System.String, System.Object, System.Object)'.
   at FastFind.FastFindArgumentParser.OnDoneParse()
   at FastFind.ArgParser.Parse(String[] args)
   at FastFind.Program.Main(String[] args)

**Comment by JohnWintellect** [comment]
Looks like you don't have the latest .NET framework installed. Go install .NET 4.6.2 and it should work. Thanks for using FastFileFinder!
